---
language: go
go:
- 1.2
- tip
env:
  global:
  - PATH=$HOME/gopath/bin:$PATH
before_install:
- go get -x github.com/tools/godep
- go get -x code.google.com/p/go.tools/cmd/cover
install: make build
script: make test
matrix:
  allow_failures:
  - go: tip
